### ISSUE TITLE
Failed to get plugins

### ISSUE THREAD

**Issue by sylvainblot** [jtyr/ansible-run_playbook#1]
Hello,

When I try your script I get:

```
Loaded callback default of type stdout, v2.0

PLAYBOOK: play.yml *************************************************************
1 plays in /tmp/test/play.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/b02472/.virtualenvs/csa_yaml/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/home/b02472/.virtualenvs/csa_yaml/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 411, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/home/b02472/.virtualenvs/csa_yaml/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 636, in _get_connection
    connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new_stdin)
  File "/home/b02472/.virtualenvs/csa_yaml/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 328, in get
    path = self.find_plugin(name)
  File "/home/b02472/.virtualenvs/csa_yaml/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 291, in find_plugin
    if not name.startswith('_'):
AttributeError: 'NoneType' object has no attribute 'startswith'

fatal: [XXX.intra]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/tmp/test/play.retry

PLAY RECAP *********************************************************************
XXX.intra : ok=0    changed=0    unreachable=0    failed=1
```

if I modify "ansible/plugins/**init**.py +291" to check for the name variable nullity before checking if its start with an uderscore i get:

```
Loaded callback default of type stdout, v2.0

PLAYBOOK: play.yml *************************************************************
1 plays in /tmp/test/play.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
fatal: [XXX.intra]: FAILED! => {"failed": true, "msg": "the connection plugin 'None' was not found"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/tmp/test/play.retry

PLAY RECAP *********************************************************************
XXX.intra : ok=0    changed=0    unreachable=0    failed=1
```

There is definitely something going wrong about plugin/module import that I can't manage to figure out. If you have any clue ?

Ansible version 2.1 installed via pip or ansible 2.0

Regards

**Comment by jtyr** [comment]
I have just tested it with Ansible 2.1 installed from OS package and all works just fine. Please could you provide more details how you created the virtualenv and how you run the script? Like that I can try to reproduce the problem and find a solution.

**Comment by sylvainblot** [comment]
I manage my virtualenv with virtualenvwrapper, I use "pip install ansible", here is the code:

```
# -*- coding: utf-8 -*-
try:
    from __main__ import display
except ImportError:
    from ansible.utils.display import Display
    display = Display()
    display.verbosity = 3

from tools.ansible.runner import Runner

runner = Runner(
    playbook='/tmp/test/play.yml',
    hosts='XXX.intra,',
    display=display,
    options={
        'subset': '~^XXX.intra',
        'become': True,
        'become_method': 'sudo',
        'become_user': 'root',
        # 'private_key_file': '/path/to/the/id_rsa',
        # 'tags': 'debug',
        # 'skip_tags': 'debug',
        'verbosity': 5,
    },
    # passwords={
    #     'become_pass': 'sudo_password',
    #     'conn_pass': 'ssh_password',
    # },
    # vault_pass='vault_password',
)

stats = runner.run()
```

Feel free to ask any information, thanks for your help.

**Comment by jtyr** [comment]
If you follow the [Usage](https://github.com/jtyr/ansible-run_playbook#usage) section of the README, does it all work for you or it throws an error?

**Comment by sylvainblot** [comment]
I set the host list to 'localhost,' and set an existing playbook and I get:

```
python run.py

PLAY ***************************************************************************

TASK [setup] *******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'startswith'
fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

```

**Comment by jtyr** [comment]
Please try to run it as it's described in the Usage section.

**Comment by sylvainblot** [comment]
Thanks for pointing that out, I did not paid attention to the working directory. The usage example is working properly, even with my own playbook.

By adding os.chdir to the env directory, I can run the run.py script from anywhere.

**Comment by jtyr** [comment]
Glad it works for you.
