### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by arbabnazar** [jtyr/ansible-run_playbook#3]
@jtyr I have downloaded your repo and run it with any change for testing and getting this error, can you please tell me how I can resolve it as I don't have much idea to run the ansible inside python. Thanks

```
vagrant@tendo:/vagrant-nfs/project/env$ ../run.py
Traceback (most recent call last):
  File "../run.py", line 140, in <module>
    main()
  File "../run.py", line 134, in main
    stats = runner.run()
  File "../run.py", line 106, in run
    self.pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 153, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 242, in run
    play_context = PlayContext(new_play, self._options, self.passwords, self._connection_lockfile.fileno())
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play_context.py", line 237, in __init__
    self.set_options(options)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play_context.py", line 303, in set_options
    self.only_tags.update(options.tags)
TypeError: 'NoneType' object is not iterable
vagrant@tendo:/vagrant-nfs/project/env$
```

**Ansible version**

```
vagrant@tendo:/vagrant-nfs/project/env$ ansible --version
ansible 2.3.0.0
  config file = /vagrant-nfs/project/env/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
vagrant@tendo:/vagrant-nfs/project/env$
```

**Comment by jtyr** [comment]
It looks like the `tags` and `skip_tags` options are required now. I have [modified](https://github.com/jtyr/ansible-run_playbook/commit/e35bdd4de432cec217f94c894e5e399ff44cb97e) the example and it works again now.

**Comment by arbabnazar** [comment]
Brilliant Thanks @jtyr

**Comment by apan-liu** [comment]
@jtyr  Hello jtyr, use 2.2.x without this problem, why 2.3.x need tags = '', skip_tags=''

**Comment by jtyr** [comment]
@liusunpan Because they did some changes in Ansible and those two are now required.

**Comment by apan-liu** [comment]
@jtyr  Not found ansible 2.3.x related to tags skip_tags in the source code
